### ISSUE TITLE
Add new code of conduct file

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/portfolio_website#1]
### Description
Add new CODE_OF_CONDUCT.md file which is standard file. You can refer sample code of conduct files.

PR requirement:
- star this repo to make it cooler
- add issue number in PR description (closes issue #_)

**Comment by VyjayantiN** [comment]
Can you please share sample code of conduct files?

**Comment by jsvigneshkanna** [comment]
@VyjayantiN , you can refer here - https://github.com/jsvigneshkanna/tailwind_ui_components

**Comment by jsvigneshkanna** [comment]
Done in PR - #2

**Comment by VyjayantiN** [comment]
It did not count to hacktoberfest 2022
