### ISSUE TITLE
Add contributors section in readme

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/portfolio_website#10]
Add the contributors section from the contribs website to the bottom of the readme

refer - https://github.com/jsvigneshkanna/tailwind_ui_components
Star the repo to make it cooler

**Comment by jsvigneshkanna** [comment]
Please go ahead @srijoy-paul , Dont forget to star the repo

**Comment by srijoy-paul** [comment]
You want that the contributor's image and info will be displayed in readme, right? @jsvigneshkanna

**Comment by srijoy-paul** [comment]
@jsvigneshkanna Can you check the PR #12  and merge.
Under hacktoberfest
