### ISSUE TITLE
Add below badge to readme

### ISSUE THREAD

**Issue by jsvigneshkanna** [jsvigneshkanna/portfolio_website#3]
Add below badge hitcount to readme.

 `[![Repo view count from Oct-27th 9PM](https://hits.dwyl.com/jsvigneshkanna/portfolio_website.svg?style=flat-square)](http://hits.dwyl.com/jsvigneshkanna/portfolio_website)`

 [![Repo view count from Oct-27th 9PM](https://hits.dwyl.com/jsvigneshkanna/portfolio_website.svg?style=flat-square)](http://hits.dwyl.com/jsvigneshkanna/portfolio_website)

Please star this repo to make it cooler

**Comment by BobinMathew** [comment]
Hi, can I do this task?

**Comment by jsvigneshkanna** [comment]
@BobinMathew please go ahead, btw dont forget to star the repo
